<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-14 at 14:16:44.
 */
$PHPUNIT = true;
require (__DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'include' . DIRECTORY_SEPARATOR . 'pageboot.php');
require ('PHPUnit/Autoload.php');
class ProfileTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Profile
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Profile();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        $db = Zend_Db_Table::getDefaultAdapter();
        $db->query('DELETE FROM "profile" WHERE first_name =\'Test\';');
    }

    /**
     * @covers Profile::loadFromId
     */
    public function testLoadFromId() {
        $this->object->loadFromId(1);
        $this->setExpectedException('Exception');
        $this->object->loadFromId(999);
    }

    /**
     * @covers Profile::getData
     */
    public function testGetData() {
        $this->object->loadFromId(1);
        $this->assertGreaterThan(0, sizeof($this->object->getData()));
    }

    /**
     * @covers Profile::setData
     */
    public function testSetData() {
        $this->object->loadFromId(1);
        $this->object->setData('11111111', 'phone');
    }

    /**
     * @covers Profile::insert
     */
    public function testInsert() {
        $this->object->setData('Test', 'first_name');
        $this->object->insert();
    }

    /**
     * @covers Profile::delete
     * @todo   Implement testDelete().
     */
    public function testDelete() {
        $this->object->setData('Test', 'first_name');
        $this->object->insert();
        $this->object->delete();
    }

    /**
     * @covers Profile::update
     */
    public function testUpdate() {
        $this->object->setData('Test', 'first_name');
        $this->object->insert();
        $this->object->setData('Test', 'last_name');
        $this->object->update();
    }

}
