<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-12 at 09:14:01.
 */
$PHPUNIT = true;
require (__DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'include' . DIRECTORY_SEPARATOR . 'pageboot.php');
require ('PHPUnit/Autoload.php');

class UserTest extends PHPUnit_Framework_TestCase {

    /**
     * @var User
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new User;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        $db = Zend_Db_Table::getDefaultAdapter();
        $db->query('DELETE FROM "user" WHERE username =\'test@test.it\';');
    }

    /**
     * @covers User::loadFromId
     */
    public function testLoadFromId() {
        $this->object->loadFromId(1);
        $this->setExpectedException('Exception');
        $this->object->loadFromId(999);
    }

    /**
     * @covers User::loadFromUsername
     */
    public function testLoadFromUsername() {
        $this->object->loadFromUsername('caiofior@gmail.com');
        $this->setExpectedException('Exception');
        $this->object->loadFromUsername(999);
    }

    /**
     * @covers User::getData
     */
    public function testGetData() {
        $this->object->loadFromId(1);
        $this->assertGreaterThan(0, sizeof($this->object->getData()));
    }

    /**
     * @covers User::setdata
     */
    public function testSetData() {
        $this->object->loadFromId(1);
        $this->object->setData('12', 'username');
    }

    /**
     * @covers User::insert
     */
    public function testInsert() {
        $this->setExpectedException('Exception');
        $this->object->insert();
    }

    /**
     * @covers User::insert
     */
    public function testInsert1() {
        $this->setExpectedException('Exception');
        $this->object->setData(array(
            'username' => 'test@test.it',
        ));
        $this->object->insert();
    }

    /**
     * @covers User::insert
     */
    public function testInsert2() {
        $this->object->setData(array(
            'username' => 'test@test.it',
            'password_new' => 'topolino'
        ));
        $this->object->insert();
        $this->setExpectedException('Exception');
        $this->object->setData(array(
            'username' => 'test@test.it',
            'password_new' => 'topolino'
        ));
        $this->object->insert();
    }

    /**
     * @covers User::delete
     */
    public function testDelete() {
        $this->object->setData(array(
            'username' => 'test@test.it',
            'password_new' => 'topolino'
        ));
        $this->object->insert();
        $this->object->loadFromUsername('test@test.it');
        $this->object->delete();
    }

    /**
     * @covers User::update
     */
    public function testUpdate() {
        $this->object->setData(array(
            'username' => 'test@test.it',
            'password_new' => 'topolino'
        ));
        $this->object->insert();
        $this->object->loadFromUsername('test@test.it');
        $this->object->setData('topolino2', 'password_new');
        $this->object->update();
    }

    
    /**
     * @covers User::getProfile
     */
    public function testGetProfile() {
        $this->object->loadFromId(1);
        $this->object->getProfile();
    }
     /**
     * @covers User::getProfile
     */
    public function testGetProfile1() {
        $this->object->setData(array(
            'username' => 'test@test.it',
            'password_new' => 'topolino'
        ));
        $this->object->insert();
        $this->object->getProfile();
    }
    
}
