<?php

namespace forest;

$PHPUNIT = true;
require (__DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'include' . DIRECTORY_SEPARATOR . 'pageboot.php');
require ('PHPUnit/Autoload.php');

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-22 at 15:34:40.
 */
class ForestTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Forest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Forest();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers User::loadFromId
     */
    public function testLoadFromId() {
        $this->setExpectedException('Exception');
        $this->object->loadFromId('s');
    }

}
