<?php

namespace forest;
$PHPUNIT = true;
require (__DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'include' . DIRECTORY_SEPARATOR . 'pageboot.php');
require ('PHPUnit/Autoload.php');
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-22 at 15:46:49.
 */
class ForestCollTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ForestColl
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ForestColl();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    /**
     * @covers ForestColl::loadAll
     */
    public function testLoadAll() {
        $this->object->loadAll();
    }
}
