<?php

namespace forest;

$PHPUNIT = true;
require (__DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'include' . DIRECTORY_SEPARATOR . 'pageboot.php');
require ('PHPUnit/Autoload.php');
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-23 at 15:33:53.
 */
class RegionCollTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var RegionColl
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new RegionColl();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    /**
     * @covers RegionColl::loadAll
     */
    public function testLoadAll() {
        $this->object->loadAll();
    }
}
