<?php

namespace forest;

$PHPUNIT = true;
require (__DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'include' . DIRECTORY_SEPARATOR . 'pageboot.php');
require ('PHPUnit/Autoload.php');
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-23 at 15:32:16.
 */
class RegionTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Region
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Region();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers forest\Region::loadFromId
     * @todo   Implement testLoadFromId().
     */
    public function testLoadFromId() {
         $this->setExpectedException('Exception');
        $this->object->loadFromId('s');
    }

}
